language: python
python:
  - "3.6"
sudo: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - elasticsearch
before_script:
    - python manage.py makemigrations
    - python manage.py migrate
script:
  coverage run --source='.' manage.py test forum
after_success:
  coveralls