 language: python # => 1

    python: # => 2

      - "2.6"

      - "2.7"

      - "3.6"


    services: # => 3

      - postgresql

    env: # => 4

      -DJANGO=1.10 DB=postgresql
    install: # => 5

      - pip install -r requirements.txt

    before_script: # => 6

      - mysql -e 'create database test;' -u root
    script: # => 7

      - python manage.py test