language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source='.' manage.py test forum --exclude-tag notworking --exclude-tag selenium
after_success:
  coveralls