# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_author',
            field=models.CharField(max_length=60),
        ),
    ]
