# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_solved',
            field=models.BooleanField(default=False),
        ),
    ]
