# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170223_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_topic',
        ),
    ]
